modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "cobblemonwildloot"
version = "${version}"
displayName = "Cobblemon Wild Loot"
authors = "LucyAzalea"
description = '''
Pokémon have a chance to drop items from their loot tables passively, in the wild, your party, or a pasture!
'''
#logoFile = ""

[[mixins]]
config = "cobblemonwildloot.mixins.json"

[[dependencies.cobblemonwildloot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonwildloot]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonwildloot]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
